version: '3.3'
services:
  minio:
    image: "minio/minio"
    container_name: minio
    ports:
      - "9000:9000"
    volumes:
      - minio_data:/data
    command: server /data
    environment:
      # Cannot browse unless the same key used in your test setUp
      AWS_REGION: us-east-1
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123

  redis-cluster-local:
    image: redis:latest
    container_name: redis-cluster-local
    volumes:
      - ./container/redis/:/data/conf
    command: bash -c "/bin/bash /data/conf/redis.sh && /bin/bash"
    tty: true
    ports:
      - 7100:7100
      - 7101:7101
      - 7102:7102
      - 7103:7103
      - 7104:7104
      - 7105:7105

  dynamodblocal:
    build: ./container/dynamodb
    container_name: dynamodb-local
    volumes:
      - dynamodb_data:/home/dynamodblocal/data
    command: ["-jar", "DynamoDBLocal.jar", "-dbPath", "./data", "-port", "8000"]
    ports:
      - "8000:8000"

  dynamodbadmin:
    image: instructure/dynamo-local-admin
    container_name: dynamodb-admin
    ports:
      - 8001:8001
    environment:
      DYNAMO_ENDPOINT: http://dynamodblocal:8000
      # Cannot browse unless the same key used in your test setUp
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: dummy-id
    depends_on:
      - dynamodblocal

  # https://hub.docker.com/r/instructure/kinesalite
  kinesalite:
    image: instructure/kinesalite
    container_name: kinesalite
    ports:
      - 4567:4567
    volumes:
      - kinesalite_data:/data

  stepfunctionslocal:
    image: amazon/aws-stepfunctions-local
    container_name: stepfunctions-local
    ports:
      - 8083:8083
    volumes:
      - stepfunctions_data:/data

  # MySQL
  db:
    image: mysql:5.7
    container_name: docker-mysql
    environment:
      MYSQL_ROOT_PASSWORD: devuser
      MYSQL_DATABASE: TestDatabase
      MYSQL_USER: devuser
      MYSQL_PASSWORD: devuser
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
    - ./container/db/data:/var/lib/mysql
    - ./container/db/my.conf:/etc/mysql/conf.d/my.conf
    - ./container/db/sql:/docker-entrypoint-initdb.d
    ports:
    - 3306:3306

  # phpMyAdmin
  phpmyadmin:
    container_name: docker-phpmyadmin
    image: phpmyadmin/phpmyadmin
    environment:
    - PMA_ARBITRARY=1
    - PMA_HOSTS=docker-mysql
    - PMA_USER=root
    - PMA_PASSWORD=devuser
    ports:
    - 8080:80
    
volumes:
  minio_data:
  dynamodb_data:
  kinesalite_data:
  stepfunctions_data: