DROP TABLE IF EXISTS TestDatabase.`SampleTable`;

CREATE TABLE IF NOT EXISTS TestDatabase.SampleTable(
    id VARCHAR(25) NOT NULL,
    data VARCHAR(20) NOT NULL,
    insert_dt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    update_dt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;